# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Lint with flake8
      run: |
        poetry run task lint
    - name: Test with pytest
      run: |
        poetry run task lint
        
  lint:

    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: some-group-name
    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Lint with flake8
      run: |
        poetry run task lint
    - name: Test with pytest
      run: |
        poetry run task lint
        
  formatter:

    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: some-group-name
    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Lint with flake8
      run: |
        poetry run task lint
    - name: Test with pytest
      run: |
        poetry run task lint
        
  security:

    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: some-group-name
    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Lint with flake8
      run: |
        poetry run task lint
    - name: Test with pytest
      run: |
        poetry run task lint
        
  test:

    runs-on: ubuntu-latest
    needs: [lint, formatter, security]
    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
    - name: Install dependencies
      run: |
        poetry install --no-root
    - name: Lint with flake8
      run: |
        poetry run task lint
    - name: Test with pytest
      run: |
        poetry run task lint


